### ISSUE TITLE
Required parameter follows optional parameter

### ISSUE THREAD

**Issue by umertoday** [surecart/wordpress-sdk#3]
Hi,
When I enabled debug mode of WordPress I am getting an Deprecated Message.  Please update :)

![error](https://user-images.githubusercontent.com/9529251/228979429-e741abd0-fa3f-4e33-903b-5d2f465ff8e2.png)

**Comment by ajgagnon** [comment]
Fixed in bdd98b072dce4924352e087848f9ad643b181d9d
