### ISSUE TITLE
Updater issue

### ISSUE THREAD

**Issue by jtamudo** [surecart/wordpress-sdk#5]
Hey there,

Im testing Surecart licensing add-on in a blank plugin. 

I followed the steps of your readme and when activating my testing plugin I can´t see a "Check for updates" option at the plugin. I don´t even know if this feature is included in the licensing add-on as there is very few information but I guess it is as there is an Updater class handling the logic. An add-on like this should be much more documented.

Wanted to ask you what extra code is required or conditions to get it functional. If no additional code is required then I have to be facing a bug/error.

Thanks.

**Comment by ajgagnon** [comment]
Hi @jtamudo 

There is no "check for updates button" as we use the built-in WordPress update checker. If you are having issues with an update not showing in the dashboard, it would be best to share your implementation so we can identify where things would be going wrong. I'm happy to help, I just need a bit more information.

**Comment by jtamudo** [comment]
Hey @ajgagnon thanks for your response.

The built-in WordPress update checker doesn´t work. This is the path im following for releasing a new version:

0-I have a blank wordpress install with the basic plugin exclusively using your code
1-Increase Plugin version at plugin main file and release.json
2-Upload the plugin new version to the product associated at Surecart 
3-Go to wordpress > dashboard > updates > check again for updates
4-Although the repository received a new version and current version at wordpress isnt up to date it says there arent new updates

*Some notes if they could interfiere at the workflow:
-The product and Surecart are located in a subfolder installation
-The wordpress where im testing the updates is a localhost installation

Here is the complete code:
-Main plugin file:
`<?php
/* 

Plugin Name: hola

Plugin URI: https://hola.com/ 

Description: Hola plugin

Version: 0.9.5

Author: hola

Author URI: https://hola.com/ 

License: GPLv2 or later 

Text Domain: hola 

*/

if ( ! class_exists( 'SureCart\Licensing\Client' ) ) {
    require_once __DIR__ . '/licensing/src/Client.php';
}

// initialize client with your plugin name.
$client = new \SureCart\Licensing\Client( 'hola', __FILE__ );

// add the pre-built license settings page.
$client->settings()->add_page( 
    [
	'type'                 => 'submenu', // Can be: menu, options, submenu.
	'parent_slug'          => 'hola', // add your plugin menu slug.
	'page_title'           => 'Manage License',
	'menu_title'           => 'Manage License',
	'capability'           => 'manage_options',
	'menu_slug'            => $client->slug . '-manage-license',
	'icon_url'             => '',
	'position'             => null,
	'parent_slug'          => '',
	'activated_redirect'   => admin_url( 'admin.php?page=my-plugin-page' ), // should you want to redirect on activation of license.
	'deactivated_redirect' => admin_url( 'admin.php?page=my-plugin-deactivation-page' ), // should you want to redirect on detactivation of license.
    ] 
);`

`release,json:
{
    "name": "hola",
    "slug": "hola",
    "author": "<a href='https://surecart.com'>SureCart</a>",
    "author_profile": "https://surecart.com",
    "version": "0.9.5",
    "requires": "5.6",
    "tested": "6.1.0",
    "requires_php": "5.3",
    "sections": {
      "description": "Hola description.",
      "changelog": "<h4>1.0 –  July 20, 2022</h4><ul><li>Bug fixes.</li><li>Initital release.</li></ul>",
      "frequently asked questions": "<h4>Question<h4><p>Answer</p>"
    }
  }`
  
Plugin structure:
![image](https://github.com/surecart/wordpress-sdk/assets/141324057/1bfc984c-4335-4654-adea-72967f1763c1)

**Comment by jtamudo** [comment]
Hey @ajgagnon thanks for your response.

The built-in WordPress update checker doesn´t work. This is the path im following for releasing a new version:

0-I have a blank wordpress install with the basic plugin exclusively using your code
1-Increase Plugin version at plugin main file and release.json
2-Upload the plugin new version to the product associated at Surecart 
3-Go to wordpress > dashboard > updates > check again for updates
4-Although the repository received a new version and current version at wordpress isnt up to date it says there arent new updates

*Some notes if they could interfiere at the workflow:
-The product and Surecart are located in a subfolder installation
-The wordpress where im testing the updates is a localhost installation

Here is the complete code:
-Main plugin file:

`
<?php
/* 

Plugin Name: hola

Plugin URI: https://hola.com/ 

Description: Hola plugin

Version: 0.9.5

Author: hola

Author URI: https://hola.com/ 

License: GPLv2 or later 

Text Domain: hola 

*/

if ( ! class_exists( 'SureCart\Licensing\Client' ) ) {
    require_once __DIR__ . '/licensing/src/Client.php';
}

// initialize client with your plugin name.
$client = new \SureCart\Licensing\Client( 'hola', __FILE__ );

// add the pre-built license settings page.
$client->settings()->add_page( 
    [
	'type'                 => 'submenu', // Can be: menu, options, submenu.
	'parent_slug'          => 'hola', // add your plugin menu slug.
	'page_title'           => 'Manage License',
	'menu_title'           => 'Manage License',
	'capability'           => 'manage_options',
	'menu_slug'            => $client->slug . '-manage-license',
	'icon_url'             => '',
	'position'             => null,
	'parent_slug'          => '',
	'activated_redirect'   => admin_url( 'admin.php?page=my-plugin-page' ), // should you want to redirect on activation of license.
	'deactivated_redirect' => admin_url( 'admin.php?page=my-plugin-deactivation-page' ), // should you want to redirect on detactivation of license.
    ] 
);
`

`release,json:
{
    "name": "hola",
    "slug": "hola",
    "author": "<a href='https://surecart.com'>SureCart</a>",
    "author_profile": "https://surecart.com",
    "version": "0.9.5",
    "requires": "5.6",
    "tested": "6.1.0",
    "requires_php": "5.3",
    "sections": {
      "description": "Hola description.",
      "changelog": "<h4>1.0 –  July 20, 2022</h4><ul><li>Bug fixes.</li><li>Initital release.</li></ul>",
      "frequently asked questions": "<h4>Question<h4><p>Answer</p>"
    }
  }`
  
Plugin structure:
![image](https://github.com/surecart/wordpress-sdk/assets/141324057/1bfc984c-4335-4654-adea-72967f1763c1)

**Comment by jtamudo** [comment]
Hey @ajgagnon thanks for your response.

The built-in WordPress update checker doesn´t work. This is the path im following for releasing a new version:

0-I have a blank wordpress install with the basic plugin exclusively using your code
1-Increase Plugin version at plugin main file and release.json
2-Upload the plugin new version to the product associated at Surecart 
3-Go to wordpress > dashboard > updates > check again for updates
4-Although the repository received a new version and current version at wordpress isnt up to date it says there arent new updates

*Some notes if they could interfiere at the workflow:
-The product and Surecart are located in a subfolder installation
-The wordpress where im testing the updates is a localhost installation

Here is the complete code:
-Main plugin file:

`<?php
/* 

Plugin Name: hola

Plugin URI: https://hola.com/ 

Description: Hola plugin

Version: 0.9.5

Author: hola

Author URI: https://hola.com/ 

License: GPLv2 or later 

Text Domain: hola 

*/

if ( ! class_exists( 'SureCart\Licensing\Client' ) ) {
    require_once __DIR__ . '/licensing/src/Client.php';
}

// initialize client with your plugin name.
$client = new \SureCart\Licensing\Client( 'hola', __FILE__ );

// add the pre-built license settings page.
$client->settings()->add_page( 
    [
	'type'                 => 'submenu', // Can be: menu, options, submenu.
	'parent_slug'          => 'hola', // add your plugin menu slug.
	'page_title'           => 'Manage License',
	'menu_title'           => 'Manage License',
	'capability'           => 'manage_options',
	'menu_slug'            => $client->slug . '-manage-license',
	'icon_url'             => '',
	'position'             => null,
	'parent_slug'          => '',
	'activated_redirect'   => admin_url( 'admin.php?page=my-plugin-page' ), // should you want to redirect on activation of license.
	'deactivated_redirect' => admin_url( 'admin.php?page=my-plugin-deactivation-page' ), // should you want to redirect on detactivation of license.
    ] 
);`

`release,json:
{
    "name": "hola",
    "slug": "hola",
    "author": "<a href='https://surecart.com'>SureCart</a>",
    "author_profile": "https://surecart.com",
    "version": "0.9.5",
    "requires": "5.6",
    "tested": "6.1.0",
    "requires_php": "5.3",
    "sections": {
      "description": "Hola description.",
      "changelog": "<h4>1.0 –  July 20, 2022</h4><ul><li>Bug fixes.</li><li>Initital release.</li></ul>",
      "frequently asked questions": "<h4>Question<h4><p>Answer</p>"
    }
  }`
  
Plugin structure:
![image](https://github.com/surecart/wordpress-sdk/assets/141324057/1bfc984c-4335-4654-adea-72967f1763c1)

**Comment by jtamudo** [comment]
Hey @ajgagnon thanks for your response.

The built-in WordPress update checker doesn´t work. This is the path im following for releasing a new version:

0-I have a blank wordpress install with the basic plugin exclusively using your code
1-Increase Plugin version at plugin main file and release.json
2-Upload the plugin new version to the product associated at Surecart 
3-Go to wordpress > dashboard > updates > check again for updates
4-Although the repository received a new version and current version at wordpress isnt up to date it says there arent new updates

*Some notes if they could interfiere at the workflow:
-The product and Surecart are located in a subfolder installation
-The wordpress where im testing the updates is a localhost installation

Here is the complete code:
-Main plugin file:

```
<?php
/* 

Plugin Name: hola

Plugin URI: https://hola.com/ 

Description: Hola plugin

Version: 0.9.5

Author: hola

Author URI: https://hola.com/ 

License: GPLv2 or later 

Text Domain: hola 

*/

if ( ! class_exists( 'SureCart\Licensing\Client' ) ) {
    require_once __DIR__ . '/licensing/src/Client.php';
}

// initialize client with your plugin name.
$client = new \SureCart\Licensing\Client( 'hola', __FILE__ );

// add the pre-built license settings page.
$client->settings()->add_page( 
    [
	'type'                 => 'submenu', // Can be: menu, options, submenu.
	'parent_slug'          => 'hola', // add your plugin menu slug.
	'page_title'           => 'Manage License',
	'menu_title'           => 'Manage License',
	'capability'           => 'manage_options',
	'menu_slug'            => $client->slug . '-manage-license',
	'icon_url'             => '',
	'position'             => null,
	'parent_slug'          => '',
	'activated_redirect'   => admin_url( 'admin.php?page=my-plugin-page' ), // should you want to redirect on activation of license.
	'deactivated_redirect' => admin_url( 'admin.php?page=my-plugin-deactivation-page' ), // should you want to redirect on detactivation of license.
    ] 
);
```


release.json:
```
{
    "name": "hola",
    "slug": "hola",
    "author": "<a href='https://surecart.com'>SureCart</a>",
    "author_profile": "https://surecart.com",
    "version": "0.9.5",
    "requires": "5.6",
    "tested": "6.1.0",
    "requires_php": "5.3",
    "sections": {
      "description": "Hola description.",
      "changelog": "<h4>1.0 –  July 20, 2022</h4><ul><li>Bug fixes.</li><li>Initital release.</li></ul>",
      "frequently asked questions": "<h4>Question<h4><p>Answer</p>"
    }
  }
```
  
Plugin structure:
![image](https://github.com/surecart/wordpress-sdk/assets/141324057/1bfc984c-4335-4654-adea-72967f1763c1)

**Comment by ajgagnon** [comment]
Thanks for the additional info. Since this is a premium feature and a support question, can you reach out to support here? 

https://surecart.com/support/support-form/

We may need to see your plugin code and get a license to test to see where things are going wrong. We are only using github issues for SDK improvements, not usage support. But we are happy to help you on our support channel.

In the meantime:

1. Can you check that your current release version is set correctly on your Edit Product page in your WordPress admin? 
2. Check to make sure the license key entered into your plugin settings page is correct.
3. Double check to make sure the license is successfully activated on your store's WP admin.
