### ISSUE TITLE
Warning at "Add new plugin"

### ISSUE THREAD

**Issue by tamudosoyyo11** [surecart/wordpress-sdk#8]
Hey there,

I´m getting this warning when using your licensing system at "Add New Plugin" option:

Warning: Undefined property: stdClass::$plugin in /home/clients/f108e2079c2f39aa6629cc3c197b2ecc/sites/mysite/wp-includes/class-wp-list-util.php on line 168

Any clue about this?

Thanks

**Comment by ajgagnon** [comment]
Thanks! This is fixed in https://github.com/surecart/wordpress-sdk/releases/tag/v1.1.2
